name: CI

on:
    push:
    workflow_dispatch:

jobs:
    build_test:
        runs-on: ubuntu-latest
    
        steps:
        - name: Checkout
          uses: actions/checkout@v4.1.6
        
        - name: Install Node
          uses: actions/setup-node@v4
          with:
            node-version: 18
        
        - name: Install Nest
          run: npm i -g @nestjs/cli
        
        - name: Install dependencies
          working-directory: ./nest/backend/
          run: npm install

        - name: Build NestJS project
          working-directory: ./nest/backend/
          run: npm run build

        
