name: CI

on:
    push:
    workflow_dispatch:

jobs:
    build_test:
        runs-on: ubuntu-latest
    
        steps:
        - name: Checkout
          uses: actions/checkout@v4.1.6
        
        - name: Install Node
          uses: actions/setup-node@v4
          with:
            node-version: 18
        
        - name: Install Nest
          run: npm i -g @nestjs/cli

        - name: Move to inner directory
          run: cd ./nest/

        - name: List items
          run: ls -al
        
        - name: Build NestJS project
          run: npm run build

        
